Repository Azure/k8s-deploy, pull requests merged in 2025-07, with the labels that each got.

#424 add server-side option for kubectl apply commands
  README.md
  action.yml
  src/strategyHelpers/blueGreen/blueGreenHelper.ts
  src/strategyHelpers/canary/podCanaryHelper.ts
  src/strategyHelpers/canary/smiCanaryHelper.ts
  src/strategyHelpers/deploymentHelper.ts
  src/types/kubectl.test.ts
  src/types/kubectl.ts
Labels: enhancement

#437 update owner team
  .github/CODEOWNERS
Labels: enhancement

#432 Added error check for canary promote actions
  src/strategyHelpers/blueGreen/blueGreenHelper.test.ts
  src/strategyHelpers/blueGreen/blueGreenHelper.ts
  src/strategyHelpers/blueGreen/deploy.test.ts
  src/strategyHelpers/blueGreen/promote.test.ts
  src/strategyHelpers/blueGreen/reject.test.ts
  src/strategyHelpers/blueGreen/route.test.ts
  src/strategyHelpers/blueGreen/smiBlueGreenHelper.test.ts
  src/strategyHelpers/canary/podCanaryHelper.test.ts
  src/strategyHelpers/canary/podCanaryHelper.ts
  src/strategyHelpers/canary/smiCanaryHelper.test.ts
  src/strategyHelpers/canary/smiCanaryHelper.ts
  src/utilities/fileUtils.test.ts
  test/unit/manifests/basic-test.yml
Labels: bug

#441 Added timeout input description to README
  README.md
  action.yml
Labels: documentation
